branch-defaults:
  master:
    environment: start-camunda-com-prod
environment-defaults:
  start-camunda-com-prod:
    branch: null
    repository: null
  start-camunda-com-test:
    branch: null
    repository: null
global:
  application_name: start_camunda_com
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Docker running
    on 64bit Amazon Linux/2.13.0
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
